# Generated by Django 4.1.2 on 2022-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='account/static/default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
